export default {
  docs: [
    'index',
    { type: 'category', label: 'A. Core truths', items: ['A-core-truths'] },
    'B-series-parallel',
    'C-batteries',
    'D-solar',
    'E-speakers',
    'F-leds',
    'G-capacitors',
    'H-wire-fuse-ground',
    'I-diodes-relays',
    'J-transistors-mosfets',
    'K-on-vs-off-board',
    'L-multimeter',
    'M-diagnostics',
    'N-common-failures',
    'O-assembly',
    'P-safety-donot',
    'Q-formulas',
    'R-poster',
    'S-final-checklist',
  ],
};
